apiVersion: v1
kind: Service
metadata:
  name: diploma-test-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: diploma-test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080